services:
  dynamodb-test:
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data-test -port 8002'
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamodb-test
    volumes:
      - './docker/dynamodb:/home/dynamodblocal/data-test'
    working_dir: /home/dynamodblocal
    ports:
      - 8002:8002
